changelog:
  exclude:
    labels:
      - "changelog-ignore"
      - "release: ready"
      - "release: done"
      - "type: chore"
      - "type: ci"
      - "type: documentation"
      - "type: refactor"
      - "type: style"
      - "type: test"
  categories:
    - title: ":warning: Breaking Changes"
      labels:
        - "breaking"
    - title: ":sparkles: New Features"
      labels:
        - "type: feature"
    - title: ":beetle: Bug Fixes"
      labels:
        - "type: fix"
    - title: ":rocket: Performance Improvements"
      labels:
        - "type: performance"
    - title: ":hammer_and_wrench: Build"
      labels:
        - "type: build"
    - title: ":dependabot: Dependencies"
      labels:
        - "type: build"
      exclude:
        authors:
          - "dependabot[bot]"
