name: Setup
description: Setup the project

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"
    - name: Create npm configuration
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
        echo "registry=https://npm.pkg.github.com/" >> .npmrc
        echo "always-auth=true" >> .npmrc
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
