name: Setup
description: Setup the project

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9
    - name: Use pnpm version
      shell: bash
      run: |
        corepack use pnpm@`pnpm -v`
    - name: Get Node version
      id: nvm
      shell: bash
      run: |
        echo "node-version=$(cat ./.nvmrc)" >> $GITHUB_OUTPUT
    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version: ${{ steps.nvm.outputs.node-version }}
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
