name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - renovate/**
      - dependabot/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run build
        run: pnpm run build
      - name: Check difference
        id: diff
        run: |
          set +e    
          git diff --exit-code dist/
          echo "has-diff=$([ $? -eq 0 ] && echo false || echo true)" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.diff.outputs.has-diff == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --all --message "build(main): update build"
          git push
