name: Pull Request Check

on:
  pull_request:
    branches: main
    types: [opened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pr:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Lint PR title
        run: |
          echo "${{ github.event.pull_request.title }}" | pnpm commitlint --verbose
