name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  statuses: read
  contents: read
  packages: read

env:
  GH_NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run prettier
        run: pnpm prettier --check "**/*.{ts,tsx,md}"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run lint
        run: pnpm lint
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run check
        run: pnpm check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run test
        run: pnpm test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Check if there is any diff
        run: git diff --exit-code dist/
