name: Release

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      release-as:
        type: string
        description: Force the release version
      pre-release:
        type: choice
        default: " "
        description: Pre-release
        options:
          - " "
          - alpha
          - beta
          - rc

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create Alpha 60 token
        id: a60-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.A60_APP_ID }}
          private-key: ${{ secrets.A60_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.a60-token.outputs.token }}
          persist-credentials: false
      - name: Release
        id: action
        uses: cyberspace7/release-action@v0.6.1
        env:
          GITHUB_TOKEN: ${{ steps.a60-token.outputs.token }}
        with:
          labels-patch: |-
            "type: fix"
            "type: performance"
          labels-minor: "type: feature"
          labels-major: "breaking"
          release-as: ${{ inputs.release-as }}
          pre-release: ${{ inputs.pre-release }}
