name: Release

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      release-as:
        type: string
        description: Force the release version
      pre-release:
        type: choice
        default: " "
        description: Pre-release
        options:
          - " "
          - alpha
          - beta
          - rc

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create Alpha 60 token
        id: a60-token
        uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1
        with:
          app-id: ${{ secrets.A60_APP_ID }}
          private-key: ${{ secrets.A60_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          token: ${{ steps.a60-token.outputs.token }}
          persist-credentials: false
      - name: Release
        id: action
        uses: cyberspace7/release-action@013ffbf7dda51cefa86e874ec813bf3e25ce0844 # v0.8.1
        env:
          GITHUB_TOKEN: ${{ steps.a60-token.outputs.token }}
        with:
          labels-patch: |-
            "type: fix"
            "type: performance"
          labels-minor: "type: feature"
          labels-major: "breaking"
          skip-pr-creation: ${{ github.event_name != 'workflow_dispatch' }}
          keep-branch-updated: ${{ github.event_name == 'workflow_dispatch' }}
          release-as: ${{ inputs.release-as }}
          pre-release: ${{ inputs.pre-release }}
